# Generated by Django 3.2.5 on 2021-08-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default="0001-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(default='CIW2G6QLE7', max_length=10, primary_key=True, serialize=False),
        ),
    ]
