# Generated by Django 3.2.5 on 2021-08-06 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20210802_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(default='5RTH6DV4DG', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.CharField(default='H9C655JO7N', max_length=10, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
