# Generated by Django 3.2.5 on 2021-08-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210806_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(default='0000000', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.CharField(default='E24FNDQ24Z', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(default='4W61Q2MS15', max_length=10, primary_key=True, serialize=False),
        ),
    ]
