# Generated by Django 3.2.5 on 2021-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210807_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(default='6A44C0ENWR', max_length=10, primary_key=True, serialize=False),
        ),
    ]
